name: deploy

on:
  push:
    branches:
      - master

env:
  GIT_USER: cayzlh
  GIT_EMAIL: ant.chenanyu@gmail.com
  DEPLOY_REPO: cayzlh/cayzlh.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Deploy with ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Cache Node Dependencies
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies.
        run: |
          npm i -g @cloudbase/cli
          npm install hexo-cli -g
          npm install

      - name: login to cloudbase
        run: |
          tcb login --apiKeyId ${{secrets.SECRET_ID}} --apiKey ${{secrets.SECRET_KEY}}

      - name: Deploy Github page.
        run: |
          hexo clean
          hexo g
          hexo d

      - name: Deploy cloudbase.
        run: |
          tcb hosting deploy ./public -r gz -e ${{secrets.ENV_ID}}

      - name: notification
        run: |
          curl https://qmsg.zendee.cn/send/${{secrets.QMSG_KEY}} -X POST -d 'msg=部署完成, 请访问 https://www.cayzlh.com/ 进行确认 '
