######## Stellar info ########
stellar:
  version: '1.1.0'
  homepage: 'https://xaoxuu.com/wiki/stellar/'
  repo: 'https://github.com/xaoxuu/hexo-theme-stellar'
  cdn_css: # Use cdn links instead of /css/main.css
  cdn_js: # Use cdn links instead of /js/main.js


######## head tags ########
open_graph:
  enable: false
  twitter_id: # for open_graph meta


######## Sidebar ########
sidebar:
  logo:
    avatar: '[config.avatar](/)' # you can set avatar link in _config.site.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post:  '[btn.blog](/)'
    wiki:  '[文档](/wiki/)'
    talking: '[动态](/talking/)'
    more: '[更多](/about/)'
  # Sidebar widgets
  widgets:
    hitokoto:
      enable: true
    # default layout in home/wiki/categories/tags/archives pages
    default: [welcome, recent, travelling] # [welcome, recent]
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: 一言
      content:
        - '<p id="hitokoto"></p>'
    travelling:
      layout: markdown
      title: 开往-友链接力
      content:
        - '[<img src="https://travellings.vercel.app/assets/logo.gif" alt="开往-友链接力" width="120">](https://travellings.now.sh)'



######## Article ########
article:
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: description
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share: # [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    max_count: 5


######## Comments ########
comments:
  service: utterances # utterances, valine
  # utterances
  # https://utteranc.es/
  utterances:
    repo: cayzlh/studious-barnacle
    issue-term: pathname
    issue-number:
    theme:
      light: github-light
      dark: github-dark
  valine:
    js: https://cdn.jsdelivr.net/gh/XuxuGood/simple-blog-cdn@main/js/Valine.min.js
    appId: # your appId
    appKey: # your appKey
    placeholder:
    requiredFields: [nick, mail]
    enableQQ: true # Unstable avatar link
    recordIP: false # Record commenter IP
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    mathJax: false
    tagMeta: [博主, 小伙伴, 访客] # 标签要显示的文字,默认'博主,小伙伴,访客'
    metaPlaceholder:
      nick: "昵称/QQ号(必填)"
      mail: "邮箱（必填，完全保密）"
      link: "网址(https://)"
    master: #md5加密后的博主邮箱
      - 6783037F2DF30EAB99F9FC256157D875
    friends: #md5加密后的小伙伴邮箱
      - 6783037F2DF30EAB99F9FC256157D875


######## Footer ########
footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/08a41b181ce68.svg"/>'
      url: https://github.com/cayzlh
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cayzlh/psychic-potato@master/image/guanyuwomen.svg"/>'
      url: https://telegram.me/Q2F5emxo
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments
  license: '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
  using: true # 显示使用的主题信息
  source: '[GitHub](https://github.com/cayzlh/cayzlh.github.io)'
  server: '[云开发CloudBase](https://cloudbase.net) & [Github Pages](https://pages.github.com)'
  icp: '粤ICP备[20058712](https://beian.miit.gov.cn/)号'
  travelling: '[<img src="https://travellings.vercel.app/assets/logo.gif" alt="开往-友链接力" width="100">](https://travellings.now.sh)'
  up_time:
    enable: true
  busuanzi:
    enable: true


######## Tag Plugins ########
tag_plugins:
  # {% note text %}
  note:
    default_color: '' # white, dark, red, orange, yellow, green, cyan, blue, purple
  # {% checkbox %}
  checkbox:
    interactive: false # enable interactive for user


######## JS Plugins ########
plugins:
  ## required plugins ##
  # jquery
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js

  ## lazyload plugins ##
  # fancybox
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
  # swiper
  swiper:
    enable: true
    css: https://unpkg.com/swiper/swiper-bundle.min.css
    js: https://unpkg.com/swiper/swiper-bundle.min.js
  # issues api
  sitesjs: /js/plugins/sites.js
  friendsjs: /js/plugins/friends.js

  ## optional plugins ##
  # preload
  preload:
    enable: true
    service: flying_pages # instant_page, flying_pages
    instant_page: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@4.1.2/js/instant_page.js
    flying_pages: https://cdn.jsdelivr.net/gh/gijo-varghese/flying-pages@2.1.2/flying-pages.min.js

  # image lazyload
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true # [hexo clean && hexo s] is required after changing this value.
    js: https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
    transition: blur # blur, fade

  # https://scrollrevealjs.org/api/reveal.html
  scrollreveal:
    enable: #true
    js: https://cdn.jsdelivr.net/npm/scrollreveal@4.0.9/dist/scrollreveal.min.js
    distance: 8px
    duration: 500 # ms
    interval: 100 # ms
    scale: 1 # 0.1~1

style:
  darkmode: auto # set 'auto' to enable, set 'false' to disable
  animated_avatar:
    animate: auto # auto, always
    background: https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.2/avatar/round/rainbow64@3x.webp

default:
  avatar: https://cdn.jsdelivr.net/gh/cayzlh/git-img-repository@master/2021/04/15554416181277441618127744725.svg
  link: https://cdn.jsdelivr.net/gh/cayzlh/git-img-repository@master/2021/04/16054316181283431618128343439.svg
  cover: https://cdn.jsdelivr.net/gh/cayzlh/git-img-repository@master/2021/04/16092916181285691618128569411.jpg
  image: https://cdn.jsdelivr.net/gh/cayzlh/git-img-repository@master/2021/04/16084216181285221618128522255.svg

talking:
  name: 🐳Ant丶
  envId: cayzlh-7g0jcpd31a34ccaf
  region: ap-guangzhou
  limit: 5
  avatar: https://cdn.jsdelivr.net/gh/cayzlh/psychic-potato@master/image/IMG_4207.JPG
  loadingImg: https://cdn.jsdelivr.net/gh/cayzlh/psychic-potato@master/image/loading.gif

